spring:
  application:
    name: realnaut-spacechips
  datasource:
    url: jdbc:h2:mem:mydb
    username: spaceships
    password: spaceships
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  cache:
    cache-names: shows-cache
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: spaceship-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
management:
  endpoints:
    web:
      exposure:
        include: caches

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
