spring:
  application:
    name: realnaut-spacechips
  datasource:
    url: jdbc:h2:mem:mydb
    username: spaceships
    password: spaceships
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
