spring:
  application:
    name: realnaut-spacechips
  datasource:
    url: jdbc:h2:mem:mydb
    username: spaceships
    password: spaceships
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  cache:
    cache-names: shows-cache
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
management:
  endpoints:
    web:
      exposure:
        include: caches